parameters:
  buildSourcePath: "**/build.psd1"
  gitVersionVariable: 'NuGetVersion'
  requiredModulesPath: RequiredModules.psd1
  artifactName: BuildOutput
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: Build
    pool: ${{ parameters.pool }}
    dependsOn: GitVersion
    workspace:
      clean: all
    variables:
      SemVer: $[dependencies.GitVersion.outputs['GitVersion.${{ parameters.gitVersionVariable }}']]
      DotNetBuild: $[dependencies.Initialize.outputs['Output.HasDotNetProject']]
      SubModuleCount: $[dependencies.Initialize.outputs['Output.SubModuleCount']]

    steps:
    - checkout: self
      clean: true
      lfs: true
      submodules: recursive
      persistCredentials: true

    # Ensure LFS updates for submodules
    - powershell: |
        git config http.https://qmdevteam.visualstudio.com.extraheader="AUTHORIZATION: bearer $(System.AccessToken)"
        git submodule foreach --recursive "ls && git lfs install --local && git lfs pull"
      displayName: 'Fetch Submodule LFS files'
      condition: gt(variables['SubModuleCount'], 0)
      name: FetchSubmoduleLFS

    - ${{ if ne('', parameters.requiredModulesPath ) }}:
      - template: Install-RequiredModule-step.yml
        parameters:
          path: $(Build.SourcesDirectory)/${{ parameters.requiredModulesPath }}

    - powershell: |
        $VersionPrefix, $VersionSuffix = "$(SemVer)" -split '[-+]', 2
        dotnet build -c Release -p:VersionPrefix=$VersionPrefix -p:VersionSuffix=$VersionSuffix
      displayName: Build Solution
      condition: eq(variables['DotNetBuild'],'True')

    - template: Build-Module-step.yml
      parameters:
        sourcePath: $(Build.SourcesDirectory)/${{ parameters.buildSourcePath }}
        destination: $(Build.BinariesDirectory)
        semVer: $(SemVer)

    - task: PublishPipelineArtifact@1
      displayName: Publish Build Output
      inputs:
        artifactName: ${{ parameters.artifactName }}
        targetPath: $(Build.BinariesDirectory)
