parameters:
  dependsOn: ['Build', 'Pester', 'ScriptAnalyzer']
  compiledArtifact: 'Compiled'
  signedArtifact: 'Signed'
  certificate: '4CBBCD74FE2AEBD080758A967D20ABF916872A95'
  stagingDirectory: '$(Build.ArtifactStagingDirectory)'
  filter: '*.*'
  pool:
    vmImage: 'windows-2019'

jobs:
  - job: Sign
    dependsOn: ${{ parameters.dependsOn }}
    pool: ${{ parameters.pool }}

    steps:
    - checkout: none # skip checking out code, we're just signing an artifact

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Build Artifacts'
      inputs:
        artifactName: ${{ parameters.artifactName }}
        downloadPath: '${{ parameters.stagingDirectory }}/${{ parameters.compiledArtifact }}'

    - template: Sign-step.yml
      parameters:
        Path: '${{ parameters.stagingDirectory }}/${{ parameters.compiledArtifact }}'
        Filter: ${{ parameters.filter }}
        Certificate: ${{ parameters.certificate }}

    - task: PublishPipelineArtifact@1
      displayName: 'RePublish Signed ${{ parameters.compiledArtifact }}'
      inputs:
        artifactName: ${{ parameters.signedArtifact }}
        pathToPublish: '${{ parameters.stagingDirectory }}/${{ parameters.artifactName }}'
